// @generated by protoc-gen-es v1.10.1 with parameter "target=ts,import_extension=none"
// @generated from file rbt/v1alpha1/options.proto (package rbt.v1alpha1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { FieldOptions as FieldOptions$1, FileOptions as FileOptions$1, Message, MessageOptions, MethodOptions as MethodOptions$1, proto3, ServiceOptions as ServiceOptions$1 } from "@bufbuild/protobuf";

/**
 * Whether and when this state type is auto-constructed.
 *
 * @generated from enum rbt.v1alpha1.AutoConstruct
 */
export enum AutoConstruct {
  /**
   * Not auto-constructed (default).
   *
   * @generated from enum value: AUTO_CONSTRUCT_UNSPECIFIED = 0;
   */
  AUTO_CONSTRUCT_UNSPECIFIED = 0,

  /**
   * One instance per authenticated user, keyed by user ID.
   *
   * @generated from enum value: PER_USER_ID = 1;
   */
  PER_USER_ID = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(AutoConstruct)
proto3.util.setEnumType(AutoConstruct, "rbt.v1alpha1.AutoConstruct", [
  { no: 0, name: "AUTO_CONSTRUCT_UNSPECIFIED" },
  { no: 1, name: "PER_USER_ID" },
]);

/**
 * @generated from message rbt.v1alpha1.ReaderMethodOptions
 */
export class ReaderMethodOptions extends Message<ReaderMethodOptions> {
  /**
   * @generated from field: rbt.v1alpha1.ReaderMethodOptions.State state = 3;
   */
  state = ReaderMethodOptions_State.DEFAULT;

  constructor(data?: PartialMessage<ReaderMethodOptions>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.ReaderMethodOptions";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 3, name: "state", kind: "enum", T: proto3.getEnumType(ReaderMethodOptions_State) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReaderMethodOptions {
    return new ReaderMethodOptions().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReaderMethodOptions {
    return new ReaderMethodOptions().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReaderMethodOptions {
    return new ReaderMethodOptions().fromJsonString(jsonString, options);
  }

  static equals(a: ReaderMethodOptions | PlainMessage<ReaderMethodOptions> | undefined, b: ReaderMethodOptions | PlainMessage<ReaderMethodOptions> | undefined): boolean {
    return proto3.util.equals(ReaderMethodOptions, a, b);
  }
}

/**
 * Option specifying how to pass the state to this method. By
 * default, unary methods get passed a unary state, but a method may
 * override that default (by setting this option to 'STREAMING') to
 * get streaming state. Likewise, by default, streaming methods get
 * streaming state, but a method may override that default (by
 * setting this option to 'UNARY') to get unary state.
 *
 * @generated from enum rbt.v1alpha1.ReaderMethodOptions.State
 */
export enum ReaderMethodOptions_State {
  /**
   * @generated from enum value: DEFAULT = 0;
   */
  DEFAULT = 0,

  /**
   * @generated from enum value: UNARY = 1;
   */
  UNARY = 1,

  /**
   * @generated from enum value: STREAMING = 2;
   */
  STREAMING = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(ReaderMethodOptions_State)
proto3.util.setEnumType(ReaderMethodOptions_State, "rbt.v1alpha1.ReaderMethodOptions.State", [
  { no: 0, name: "DEFAULT" },
  { no: 1, name: "UNARY" },
  { no: 2, name: "STREAMING" },
]);

/**
 * @generated from message rbt.v1alpha1.WriterMethodOptions
 */
export class WriterMethodOptions extends Message<WriterMethodOptions> {
  /**
   * If set, indicates this writer can be used to construct a new actor,
   * and an actor can not be _implicitly_ constructed but instead
   * must be constructed via a constructor.
   *
   * @generated from field: optional rbt.v1alpha1.ConstructorMethodOptions constructor = 2;
   */
  constructor$?: ConstructorMethodOptions;

  constructor(data?: PartialMessage<WriterMethodOptions>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.WriterMethodOptions";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "constructor", kind: "message", T: ConstructorMethodOptions, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WriterMethodOptions {
    return new WriterMethodOptions().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WriterMethodOptions {
    return new WriterMethodOptions().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WriterMethodOptions {
    return new WriterMethodOptions().fromJsonString(jsonString, options);
  }

  static equals(a: WriterMethodOptions | PlainMessage<WriterMethodOptions> | undefined, b: WriterMethodOptions | PlainMessage<WriterMethodOptions> | undefined): boolean {
    return proto3.util.equals(WriterMethodOptions, a, b);
  }
}

/**
 * @generated from message rbt.v1alpha1.TransactionMethodOptions
 */
export class TransactionMethodOptions extends Message<TransactionMethodOptions> {
  /**
   * If set, indicates this transaction can be used to construct a new actor,
   * and an actor can not be _implicitly_ constructed but instead
   * must be constructed via a constructor.
   *
   * @generated from field: optional rbt.v1alpha1.ConstructorMethodOptions constructor = 2;
   */
  constructor$?: ConstructorMethodOptions;

  /**
   * How the transaction holds the lock on its own state while it
   * runs. Required: code generation refuses a transaction that has
   * not chosen one.
   *
   * @generated from oneof rbt.v1alpha1.TransactionMethodOptions.mode
   */
  mode: {
    /**
     * @generated from field: rbt.v1alpha1.ExclusiveTransactionMethodOptions exclusive = 3;
     */
    value: ExclusiveTransactionMethodOptions;
    case: "exclusive";
  } | {
    /**
     * @generated from field: rbt.v1alpha1.SharedTransactionMethodOptions shared = 4;
     */
    value: SharedTransactionMethodOptions;
    case: "shared";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<TransactionMethodOptions>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.TransactionMethodOptions";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "constructor", kind: "message", T: ConstructorMethodOptions, opt: true },
    { no: 3, name: "exclusive", kind: "message", T: ExclusiveTransactionMethodOptions, oneof: "mode" },
    { no: 4, name: "shared", kind: "message", T: SharedTransactionMethodOptions, oneof: "mode" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TransactionMethodOptions {
    return new TransactionMethodOptions().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TransactionMethodOptions {
    return new TransactionMethodOptions().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TransactionMethodOptions {
    return new TransactionMethodOptions().fromJsonString(jsonString, options);
  }

  static equals(a: TransactionMethodOptions | PlainMessage<TransactionMethodOptions> | undefined, b: TransactionMethodOptions | PlainMessage<TransactionMethodOptions> | undefined): boolean {
    return proto3.util.equals(TransactionMethodOptions, a, b);
  }
}

/**
 * A transaction that takes the lock on its own state exclusive from
 * the start, so that concurrent callers of the same state queue
 * behind it. The choice for a transaction that writes its own state,
 * which is most of them: two such transactions can never run to
 * completion concurrently anyway, and starting shared is what lets
 * them deadlock on the upgrade.
 *
 * Nothing here yet, but is a placeholder for describing things.
 *
 * @generated from message rbt.v1alpha1.ExclusiveTransactionMethodOptions
 */
export class ExclusiveTransactionMethodOptions extends Message<ExclusiveTransactionMethodOptions> {
  constructor(data?: PartialMessage<ExclusiveTransactionMethodOptions>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.ExclusiveTransactionMethodOptions";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExclusiveTransactionMethodOptions {
    return new ExclusiveTransactionMethodOptions().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExclusiveTransactionMethodOptions {
    return new ExclusiveTransactionMethodOptions().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExclusiveTransactionMethodOptions {
    return new ExclusiveTransactionMethodOptions().fromJsonString(jsonString, options);
  }

  static equals(a: ExclusiveTransactionMethodOptions | PlainMessage<ExclusiveTransactionMethodOptions> | undefined, b: ExclusiveTransactionMethodOptions | PlainMessage<ExclusiveTransactionMethodOptions> | undefined): boolean {
    return proto3.util.equals(ExclusiveTransactionMethodOptions, a, b);
  }
}

/**
 * A transaction that takes the lock on its own state shared and
 * upgrades it to exclusive only if it writes its own state, so that
 * callers proceed concurrently while none of them writes it. The
 * choice for a transaction that mostly reads its own state while
 * writing others, such as the root of a tree of states that every
 * call descends through.
 *
 * Nothing here yet, but is a placeholder for describing things.
 *
 * @generated from message rbt.v1alpha1.SharedTransactionMethodOptions
 */
export class SharedTransactionMethodOptions extends Message<SharedTransactionMethodOptions> {
  constructor(data?: PartialMessage<SharedTransactionMethodOptions>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.SharedTransactionMethodOptions";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SharedTransactionMethodOptions {
    return new SharedTransactionMethodOptions().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SharedTransactionMethodOptions {
    return new SharedTransactionMethodOptions().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SharedTransactionMethodOptions {
    return new SharedTransactionMethodOptions().fromJsonString(jsonString, options);
  }

  static equals(a: SharedTransactionMethodOptions | PlainMessage<SharedTransactionMethodOptions> | undefined, b: SharedTransactionMethodOptions | PlainMessage<SharedTransactionMethodOptions> | undefined): boolean {
    return proto3.util.equals(SharedTransactionMethodOptions, a, b);
  }
}

/**
 * Nothing here yet, but is a placeholder for describing things.
 *
 * @generated from message rbt.v1alpha1.WorkflowMethodOptions
 */
export class WorkflowMethodOptions extends Message<WorkflowMethodOptions> {
  constructor(data?: PartialMessage<WorkflowMethodOptions>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.WorkflowMethodOptions";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WorkflowMethodOptions {
    return new WorkflowMethodOptions().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WorkflowMethodOptions {
    return new WorkflowMethodOptions().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WorkflowMethodOptions {
    return new WorkflowMethodOptions().fromJsonString(jsonString, options);
  }

  static equals(a: WorkflowMethodOptions | PlainMessage<WorkflowMethodOptions> | undefined, b: WorkflowMethodOptions | PlainMessage<WorkflowMethodOptions> | undefined): boolean {
    return proto3.util.equals(WorkflowMethodOptions, a, b);
  }
}

/**
 * Nothing here yet, but is a placeholder for describing things like
 * "recallable" constructors, etc.
 *
 * @generated from message rbt.v1alpha1.ConstructorMethodOptions
 */
export class ConstructorMethodOptions extends Message<ConstructorMethodOptions> {
  constructor(data?: PartialMessage<ConstructorMethodOptions>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.ConstructorMethodOptions";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ConstructorMethodOptions {
    return new ConstructorMethodOptions().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ConstructorMethodOptions {
    return new ConstructorMethodOptions().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ConstructorMethodOptions {
    return new ConstructorMethodOptions().fromJsonString(jsonString, options);
  }

  static equals(a: ConstructorMethodOptions | PlainMessage<ConstructorMethodOptions> | undefined, b: ConstructorMethodOptions | PlainMessage<ConstructorMethodOptions> | undefined): boolean {
    return proto3.util.equals(ConstructorMethodOptions, a, b);
  }
}

/**
 * MCP (Model Context Protocol) options for exposing methods as
 * tools/resources.
 *
 * @generated from message rbt.v1alpha1.McpMethodOptions
 */
export class McpMethodOptions extends Message<McpMethodOptions> {
  /**
   * Expose this method as an MCP tool.
   *
   * @generated from field: optional bool tool = 1;
   */
  tool?: boolean;

  /**
   * Expose this method as an MCP resource.
   *
   * @generated from field: optional bool resource = 2;
   */
  resource?: boolean;

  /**
   * Custom name for the tool/resource (defaults to method name).
   *
   * @generated from field: optional string name = 3;
   */
  name?: string;

  /**
   * Deprecated: write `MethodOptions.description` instead. Read as a
   * fallback when it is the only description present.
   *
   * @generated from field: optional string description = 4 [deprecated = true];
   * @deprecated
   */
  description?: string;

  /**
   * Display title for the tool/resource.
   *
   * @generated from field: optional string title = 5;
   */
  title?: string;

  constructor(data?: PartialMessage<McpMethodOptions>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.McpMethodOptions";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "tool", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 2, name: "resource", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): McpMethodOptions {
    return new McpMethodOptions().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): McpMethodOptions {
    return new McpMethodOptions().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): McpMethodOptions {
    return new McpMethodOptions().fromJsonString(jsonString, options);
  }

  static equals(a: McpMethodOptions | PlainMessage<McpMethodOptions> | undefined, b: McpMethodOptions | PlainMessage<McpMethodOptions> | undefined): boolean {
    return proto3.util.equals(McpMethodOptions, a, b);
  }
}

/**
 * UI definition: a UI() method generates an MCP tool + resource
 * but no backend RPC.
 *
 * @generated from message rbt.v1alpha1.UI
 */
export class UI extends Message<UI> {
  /**
   * Method name (e.g., "show_clicker").
   *
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * Display title for the UI.
   *
   * @generated from field: string title = 2;
   */
  title = "";

  /**
   * Optional description.
   *
   * @generated from field: optional string description = 3;
   */
  description?: string;

  /**
   * Relative path to the web app assets.
   *
   * @generated from field: string path = 4;
   */
  path = "";

  /**
   * Name of the generated request message type (empty if
   * no request).
   *
   * @generated from field: optional string request_message = 5;
   */
  requestMessage?: string;

  /**
   * Override for the build artifact path. Defaults to
   * inserting `dist/` after the first component of `path`.
   *
   * @generated from field: optional string artifact_path = 6;
   */
  artifactPath?: string;

  constructor(data?: PartialMessage<UI>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.UI";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "request_message", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "artifact_path", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UI {
    return new UI().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UI {
    return new UI().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UI {
    return new UI().fromJsonString(jsonString, options);
  }

  static equals(a: UI | PlainMessage<UI> | undefined, b: UI | PlainMessage<UI> | undefined): boolean {
    return proto3.util.equals(UI, a, b);
  }
}

/**
 * @generated from message rbt.v1alpha1.MethodOptions
 */
export class MethodOptions extends Message<MethodOptions> {
  /**
   * The `kind` field specifies what kind of reboot function the method is.
   * Method kind specific annotations are set in the nested object.
   *
   * @generated from oneof rbt.v1alpha1.MethodOptions.kind
   */
  kind: {
    /**
     * @generated from field: rbt.v1alpha1.ReaderMethodOptions reader = 1;
     */
    value: ReaderMethodOptions;
    case: "reader";
  } | {
    /**
     * @generated from field: rbt.v1alpha1.WriterMethodOptions writer = 2;
     */
    value: WriterMethodOptions;
    case: "writer";
  } | {
    /**
     * @generated from field: rbt.v1alpha1.TransactionMethodOptions transaction = 3;
     */
    value: TransactionMethodOptions;
    case: "transaction";
  } | {
    /**
     * TODO: SagaMethodOptions saga = 5;
     *
     * @generated from field: rbt.v1alpha1.WorkflowMethodOptions workflow = 4;
     */
    value: WorkflowMethodOptions;
    case: "workflow";
  } | { case: undefined; value?: undefined } = { case: undefined };

  /**
   * Possible error message types that may be raised.
   *
   * Name resolution is done in accordance with proto3 definitions,
   * see comment in ServiceOptions for more details.
   *
   * @generated from field: repeated string errors = 7;
   */
  errors: string[] = [];

  /**
   * MCP options for exposing this method as a tool or resource.
   *
   * @generated from field: optional rbt.v1alpha1.McpMethodOptions mcp = 9;
   */
  mcp?: McpMethodOptions;

  /**
   * What this method does, in the author's own words.
   *
   * @generated from field: optional string description = 10;
   */
  description?: string;

  constructor(data?: PartialMessage<MethodOptions>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.MethodOptions";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "reader", kind: "message", T: ReaderMethodOptions, oneof: "kind" },
    { no: 2, name: "writer", kind: "message", T: WriterMethodOptions, oneof: "kind" },
    { no: 3, name: "transaction", kind: "message", T: TransactionMethodOptions, oneof: "kind" },
    { no: 4, name: "workflow", kind: "message", T: WorkflowMethodOptions, oneof: "kind" },
    { no: 7, name: "errors", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 9, name: "mcp", kind: "message", T: McpMethodOptions, opt: true },
    { no: 10, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MethodOptions {
    return new MethodOptions().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MethodOptions {
    return new MethodOptions().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MethodOptions {
    return new MethodOptions().fromJsonString(jsonString, options);
  }

  static equals(a: MethodOptions | PlainMessage<MethodOptions> | undefined, b: MethodOptions | PlainMessage<MethodOptions> | undefined): boolean {
    return proto3.util.equals(MethodOptions, a, b);
  }
}

/**
 * @generated from message rbt.v1alpha1.ServiceOptions
 */
export class ServiceOptions extends Message<ServiceOptions> {
  /**
   * The name of the Reboot state `message` that this service supplies methods
   * for. May be omitted if the system's default naming convention is
   * acceptable. If supplied, the name is looked up using protobuf's normal
   * rules: relative names are resolved in the same package, while absolute
   * names may refer to any package.
   *
   * @generated from field: string state = 1;
   */
  state = "";

  /**
   * Whether or not this service can be default constructed via just
   * calling a writer even if some methods are specified as constructors.
   *
   * @generated from field: bool default_constructible = 2;
   */
  defaultConstructible = false;

  constructor(data?: PartialMessage<ServiceOptions>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.ServiceOptions";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "state", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "default_constructible", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServiceOptions {
    return new ServiceOptions().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServiceOptions {
    return new ServiceOptions().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServiceOptions {
    return new ServiceOptions().fromJsonString(jsonString, options);
  }

  static equals(a: ServiceOptions | PlainMessage<ServiceOptions> | undefined, b: ServiceOptions | PlainMessage<ServiceOptions> | undefined): boolean {
    return proto3.util.equals(ServiceOptions, a, b);
  }
}

/**
 * @generated from message rbt.v1alpha1.StateOptions
 */
export class StateOptions extends Message<StateOptions> {
  /**
   * A list of names of Reboot method definition `service`s that provide this
   * state `message` with methods. May be omitted if the system's default naming
   * convention is acceptable. Each named service must, in turn, have their
   * `state` option set to point at this state.
   *
   * @generated from field: repeated string implements = 1;
   */
  implements: string[] = [];

  /**
   * UIs associated with this state type (from UI() methods).
   *
   * @generated from field: repeated rbt.v1alpha1.UI uis = 2;
   */
  uis: UI[] = [];

  /**
   * Whether and when this state type is auto-constructed.
   *
   * @generated from field: rbt.v1alpha1.AutoConstruct auto_construct = 3;
   */
  autoConstruct = AutoConstruct.AUTO_CONSTRUCT_UNSPECIFIED;

  /**
   * Marks this state type's effects as "trusted": its methods are
   * known-good and skip effect-validation re-runs unless
   * `RBT_VALIDATE_TRUSTED_EFFECTS` is set. See
   * https://github.com/reboot-dev/mono/issues/4499.
   *
   * @generated from field: bool trusted_effects = 4;
   */
  trustedEffects = false;

  /**
   * What the state type does, in the author's own words. Worth
   * writing about the parts a reader cannot derive, such as what it
   * is the consistency boundary for, rather than restating the
   * methods listed beside it.
   *
   * @generated from field: optional string description = 5;
   */
  description?: string;

  constructor(data?: PartialMessage<StateOptions>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.StateOptions";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "implements", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "uis", kind: "message", T: UI, repeated: true },
    { no: 3, name: "auto_construct", kind: "enum", T: proto3.getEnumType(AutoConstruct) },
    { no: 4, name: "trusted_effects", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StateOptions {
    return new StateOptions().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StateOptions {
    return new StateOptions().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StateOptions {
    return new StateOptions().fromJsonString(jsonString, options);
  }

  static equals(a: StateOptions | PlainMessage<StateOptions> | undefined, b: StateOptions | PlainMessage<StateOptions> | undefined): boolean {
    return proto3.util.equals(StateOptions, a, b);
  }
}

/**
 * @generated from message rbt.v1alpha1.FileOptions
 */
export class FileOptions extends Message<FileOptions> {
  /**
   * Path to TypeScript schema that we want to be able to import in
   * our generated code.
   *
   * @generated from field: optional string zod = 1;
   */
  zod?: string;

  /**
   * Path to Python schema that we want to be able to import in
   * our generated code.
   *
   * @generated from field: optional string pydantic = 2;
   */
  pydantic?: string;

  /**
   * A hex SHA-256 of the proto text this file held before this
   * option was appended, which is what a pydantic API generates
   * to: written into the generated code, so that whoever has the
   * API in hand can tell whether the generated code came from it.
   *
   * @generated from field: optional string api_digest = 3;
   */
  apiDigest?: string;

  constructor(data?: PartialMessage<FileOptions>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.FileOptions";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "zod", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "pydantic", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "api_digest", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FileOptions {
    return new FileOptions().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FileOptions {
    return new FileOptions().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FileOptions {
    return new FileOptions().fromJsonString(jsonString, options);
  }

  static equals(a: FileOptions | PlainMessage<FileOptions> | undefined, b: FileOptions | PlainMessage<FileOptions> | undefined): boolean {
    return proto3.util.equals(FileOptions, a, b);
  }
}

/**
 * @generated from message rbt.v1alpha1.FieldOptions
 */
export class FieldOptions extends Message<FieldOptions> {
  /**
   * The fully qualified Pydantic type for this field if the input schema
   * is from Pydantic.
   *
   * @generated from field: string pydantic_type = 1;
   */
  pydanticType = "";

  /**
   * Whether this field is required (has no default value).
   * Set when generating proto from Pydantic and Zod.
   *
   * @generated from field: bool required = 2;
   */
  required = false;

  constructor(data?: PartialMessage<FieldOptions>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.FieldOptions";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pydantic_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "required", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FieldOptions {
    return new FieldOptions().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FieldOptions {
    return new FieldOptions().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FieldOptions {
    return new FieldOptions().fromJsonString(jsonString, options);
  }

  static equals(a: FieldOptions | PlainMessage<FieldOptions> | undefined, b: FieldOptions | PlainMessage<FieldOptions> | undefined): boolean {
    return proto3.util.equals(FieldOptions, a, b);
  }
}

/**
 * TODO: once these options are stable, register field numbers for them in the
 *       official protobuf global extension registry:
 *       https://github.com/protocolbuffers/protobuf/blob/main/docs/options.md
 *       For now we use the 50000-99999 range for "in-house" applications.
 *
 * @generated from extension: rbt.v1alpha1.MethodOptions method = 50000;
 */
export const method = proto3.makeExtension<MethodOptions$1, MethodOptions>(
  "rbt.v1alpha1.method", 
  MethodOptions$1, 
  () => ({ no: 50000, kind: "message", T: MethodOptions }),
);

/**
 * TODO: once these options are stable, register field numbers for them in the
 *       official protobuf global extension registry:
 *       https://github.com/protocolbuffers/protobuf/blob/main/docs/options.md
 *       For now we use the 50000-99999 range for "in-house" applications.
 *
 * @generated from extension: rbt.v1alpha1.ServiceOptions service = 50000;
 */
export const service = proto3.makeExtension<ServiceOptions$1, ServiceOptions>(
  "rbt.v1alpha1.service", 
  ServiceOptions$1, 
  () => ({ no: 50000, kind: "message", T: ServiceOptions }),
);

/**
 * TODO: once these options are stable, register field numbers for them in the
 *       official protobuf global extension registry:
 *       https://github.com/protocolbuffers/protobuf/blob/main/docs/options.md
 *       For now we use the 50000-99999 range for "in-house" applications.
 *
 * @generated from extension: rbt.v1alpha1.StateOptions state = 50000;
 */
export const state = proto3.makeExtension<MessageOptions, StateOptions>(
  "rbt.v1alpha1.state", 
  MessageOptions, 
  () => ({ no: 50000, kind: "message", T: StateOptions }),
);

/**
 * TODO: once these options are stable, register field numbers for them in the
 *       official protobuf global extension registry:
 *       https://github.com/protocolbuffers/protobuf/blob/main/docs/options.md
 *       For now we use the 50000-99999 range for "in-house" applications.
 *
 * @generated from extension: rbt.v1alpha1.FileOptions file = 50000;
 */
export const file = proto3.makeExtension<FileOptions$1, FileOptions>(
  "rbt.v1alpha1.file", 
  FileOptions$1, 
  () => ({ no: 50000, kind: "message", T: FileOptions }),
);

/**
 * TODO: once these options are stable, register field numbers for them in the
 *       official protobuf global extension registry:
 *       https://github.com/protocolbuffers/protobuf/blob/main/docs/options.md
 *       For now we use the 50000-99999 range for "in-house" applications.
 *
 * @generated from extension: rbt.v1alpha1.FieldOptions field = 50000;
 */
export const field = proto3.makeExtension<FieldOptions$1, FieldOptions>(
  "rbt.v1alpha1.field", 
  FieldOptions$1, 
  () => ({ no: 50000, kind: "message", T: FieldOptions }),
);

