// @generated by protoc-gen-es v1.10.1 with parameter "target=ts,import_extension=none"
// @generated from file rbt/v1alpha1/tasks.proto (package rbt.v1alpha1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Any, Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message rbt.v1alpha1.TaskId
 */
export class TaskId extends Message<TaskId> {
  /**
   * @generated from field: string state_type = 1;
   */
  stateType = "";

  /**
   * @generated from field: string state_ref = 2;
   */
  stateRef = "";

  /**
   * @generated from field: bytes task_uuid = 3;
   */
  taskUuid = new Uint8Array(0);

  constructor(data?: PartialMessage<TaskId>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.TaskId";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "state_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "state_ref", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "task_uuid", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TaskId {
    return new TaskId().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TaskId {
    return new TaskId().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TaskId {
    return new TaskId().fromJsonString(jsonString, options);
  }

  static equals(a: TaskId | PlainMessage<TaskId> | undefined, b: TaskId | PlainMessage<TaskId> | undefined): boolean {
    return proto3.util.equals(TaskId, a, b);
  }
}

/**
 * @generated from message rbt.v1alpha1.TaskInfo
 */
export class TaskInfo extends Message<TaskInfo> {
  /**
   * @generated from field: rbt.v1alpha1.TaskInfo.Status status = 1;
   */
  status = TaskInfo_Status.UNKNOWN;

  /**
   * @generated from field: rbt.v1alpha1.TaskId task_id = 2;
   */
  taskId?: TaskId;

  /**
   * @generated from field: string method = 3;
   */
  method = "";

  /**
   * When we got to this state. Always there.
   *
   * @generated from field: google.protobuf.Timestamp occurred_at = 4;
   */
  occurredAt?: Timestamp;

  /**
   * When we expect to next transition. Only for scheduled statuses.
   *
   * @generated from field: google.protobuf.Timestamp scheduled_at = 5;
   */
  scheduledAt?: Timestamp;

  /**
   * The number of completed iterations the task has gone through. Note
   * that tasks that don't loop are still considered to complete one
   * iteration.
   *
   * @generated from field: uint64 iterations = 6;
   */
  iterations = protoInt64.zero;

  /**
   * Number of runs that failed in a retry loop recently (since the server
   * most recently came up).
   *
   * @generated from field: uint64 num_runs_failed_recently = 7;
   */
  numRunsFailedRecently = protoInt64.zero;

  constructor(data?: PartialMessage<TaskInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.TaskInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "enum", T: proto3.getEnumType(TaskInfo_Status) },
    { no: 2, name: "task_id", kind: "message", T: TaskId },
    { no: 3, name: "method", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "occurred_at", kind: "message", T: Timestamp },
    { no: 5, name: "scheduled_at", kind: "message", T: Timestamp },
    { no: 6, name: "iterations", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 7, name: "num_runs_failed_recently", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TaskInfo {
    return new TaskInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TaskInfo {
    return new TaskInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TaskInfo {
    return new TaskInfo().fromJsonString(jsonString, options);
  }

  static equals(a: TaskInfo | PlainMessage<TaskInfo> | undefined, b: TaskInfo | PlainMessage<TaskInfo> | undefined): boolean {
    return proto3.util.equals(TaskInfo, a, b);
  }
}

/**
 * @generated from enum rbt.v1alpha1.TaskInfo.Status
 */
export enum TaskInfo_Status {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: STARTED = 1;
   */
  STARTED = 1,

  /**
   * If task is SCHEDULED, it means that it was scheduled and is
   * waiting to be executed for the first time.
   *
   * @generated from enum value: SCHEDULED = 2;
   */
  SCHEDULED = 2,

  /**
   * If task is SCHEDULED_RETRY, it means that it had started, but
   * failed, and is now waiting for some backoff before executing a
   * retry.
   *
   * @generated from enum value: SCHEDULED_RETRY = 3;
   */
  SCHEDULED_RETRY = 3,

  /**
   * If a task has status SCHEDULED_ITERATION, it means that it had
   * started, but is now waiting for the next iteration of its loop to
   * begin.
   *
   * @generated from enum value: SCHEDULED_ITERATION = 6;
   */
  SCHEDULED_ITERATION = 6,

  /**
   * If task is CANCELLED, it means that it was cancelled by a caller
   * before it was completed.
   *
   * @generated from enum value: CANCELLED = 4;
   */
  CANCELLED = 4,

  /**
   * If task is ABORTED, it means that it began executing but
   * returned a declared error (i.e. one that will not be retried).
   *
   * @generated from enum value: ABORTED = 7;
   */
  ABORTED = 7,

  /**
   * If task is COMPLETED, it means that it was executed and completed
   * successfully.
   *
   * @generated from enum value: COMPLETED = 5;
   */
  COMPLETED = 5,
}
// Retrieve enum metadata with: proto3.getEnumType(TaskInfo_Status)
proto3.util.setEnumType(TaskInfo_Status, "rbt.v1alpha1.TaskInfo.Status", [
  { no: 0, name: "UNKNOWN" },
  { no: 1, name: "STARTED" },
  { no: 2, name: "SCHEDULED" },
  { no: 3, name: "SCHEDULED_RETRY" },
  { no: 6, name: "SCHEDULED_ITERATION" },
  { no: 4, name: "CANCELLED" },
  { no: 7, name: "ABORTED" },
  { no: 5, name: "COMPLETED" },
]);

/**
 * @generated from message rbt.v1alpha1.WaitRequest
 */
export class WaitRequest extends Message<WaitRequest> {
  /**
   * @generated from field: rbt.v1alpha1.TaskId task_id = 1;
   */
  taskId?: TaskId;

  constructor(data?: PartialMessage<WaitRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.WaitRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "task_id", kind: "message", T: TaskId },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WaitRequest {
    return new WaitRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WaitRequest {
    return new WaitRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WaitRequest {
    return new WaitRequest().fromJsonString(jsonString, options);
  }

  static equals(a: WaitRequest | PlainMessage<WaitRequest> | undefined, b: WaitRequest | PlainMessage<WaitRequest> | undefined): boolean {
    return proto3.util.equals(WaitRequest, a, b);
  }
}

/**
 * @generated from message rbt.v1alpha1.TaskResponseOrError
 */
export class TaskResponseOrError extends Message<TaskResponseOrError> {
  /**
   * @generated from oneof rbt.v1alpha1.TaskResponseOrError.response_or_error
   */
  responseOrError: {
    /**
     * @generated from field: google.protobuf.Any response = 1;
     */
    value: Any;
    case: "response";
  } | {
    /**
     * @generated from field: google.protobuf.Any error = 2;
     */
    value: Any;
    case: "error";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<TaskResponseOrError>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.TaskResponseOrError";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "response", kind: "message", T: Any, oneof: "response_or_error" },
    { no: 2, name: "error", kind: "message", T: Any, oneof: "response_or_error" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TaskResponseOrError {
    return new TaskResponseOrError().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TaskResponseOrError {
    return new TaskResponseOrError().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TaskResponseOrError {
    return new TaskResponseOrError().fromJsonString(jsonString, options);
  }

  static equals(a: TaskResponseOrError | PlainMessage<TaskResponseOrError> | undefined, b: TaskResponseOrError | PlainMessage<TaskResponseOrError> | undefined): boolean {
    return proto3.util.equals(TaskResponseOrError, a, b);
  }
}

/**
 * @generated from message rbt.v1alpha1.WaitResponse
 */
export class WaitResponse extends Message<WaitResponse> {
  /**
   * @generated from field: rbt.v1alpha1.TaskResponseOrError response_or_error = 1;
   */
  responseOrError?: TaskResponseOrError;

  constructor(data?: PartialMessage<WaitResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.WaitResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "response_or_error", kind: "message", T: TaskResponseOrError },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WaitResponse {
    return new WaitResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WaitResponse {
    return new WaitResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WaitResponse {
    return new WaitResponse().fromJsonString(jsonString, options);
  }

  static equals(a: WaitResponse | PlainMessage<WaitResponse> | undefined, b: WaitResponse | PlainMessage<WaitResponse> | undefined): boolean {
    return proto3.util.equals(WaitResponse, a, b);
  }
}

/**
 * @generated from message rbt.v1alpha1.ListTasksRequest
 */
export class ListTasksRequest extends Message<ListTasksRequest> {
  /**
   * If set, only return pending tasks held by the given server ID. If not
   * set (or left at default), return all pending tasks held by all servers.
   *
   * @generated from field: optional string only_server_id = 1;
   */
  onlyServerId?: string;

  constructor(data?: PartialMessage<ListTasksRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.ListTasksRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "only_server_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListTasksRequest {
    return new ListTasksRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListTasksRequest {
    return new ListTasksRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListTasksRequest {
    return new ListTasksRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListTasksRequest | PlainMessage<ListTasksRequest> | undefined, b: ListTasksRequest | PlainMessage<ListTasksRequest> | undefined): boolean {
    return proto3.util.equals(ListTasksRequest, a, b);
  }
}

/**
 * @generated from message rbt.v1alpha1.ListTasksResponse
 */
export class ListTasksResponse extends Message<ListTasksResponse> {
  /**
   * @generated from field: repeated rbt.v1alpha1.TaskInfo tasks = 1;
   */
  tasks: TaskInfo[] = [];

  constructor(data?: PartialMessage<ListTasksResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.ListTasksResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "tasks", kind: "message", T: TaskInfo, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListTasksResponse {
    return new ListTasksResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListTasksResponse {
    return new ListTasksResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListTasksResponse {
    return new ListTasksResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListTasksResponse | PlainMessage<ListTasksResponse> | undefined, b: ListTasksResponse | PlainMessage<ListTasksResponse> | undefined): boolean {
    return proto3.util.equals(ListTasksResponse, a, b);
  }
}

/**
 * @generated from message rbt.v1alpha1.CancelTaskRequest
 */
export class CancelTaskRequest extends Message<CancelTaskRequest> {
  /**
   * @generated from field: rbt.v1alpha1.TaskId task_id = 1;
   */
  taskId?: TaskId;

  constructor(data?: PartialMessage<CancelTaskRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.CancelTaskRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "task_id", kind: "message", T: TaskId },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancelTaskRequest {
    return new CancelTaskRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancelTaskRequest {
    return new CancelTaskRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancelTaskRequest {
    return new CancelTaskRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CancelTaskRequest | PlainMessage<CancelTaskRequest> | undefined, b: CancelTaskRequest | PlainMessage<CancelTaskRequest> | undefined): boolean {
    return proto3.util.equals(CancelTaskRequest, a, b);
  }
}

/**
 * @generated from message rbt.v1alpha1.CancelTaskResponse
 */
export class CancelTaskResponse extends Message<CancelTaskResponse> {
  /**
   * @generated from field: rbt.v1alpha1.CancelTaskResponse.Status status = 1;
   */
  status = CancelTaskResponse_Status.OK;

  constructor(data?: PartialMessage<CancelTaskResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rbt.v1alpha1.CancelTaskResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "enum", T: proto3.getEnumType(CancelTaskResponse_Status) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancelTaskResponse {
    return new CancelTaskResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancelTaskResponse {
    return new CancelTaskResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancelTaskResponse {
    return new CancelTaskResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CancelTaskResponse | PlainMessage<CancelTaskResponse> | undefined, b: CancelTaskResponse | PlainMessage<CancelTaskResponse> | undefined): boolean {
    return proto3.util.equals(CancelTaskResponse, a, b);
  }
}

/**
 * @generated from enum rbt.v1alpha1.CancelTaskResponse.Status
 */
export enum CancelTaskResponse_Status {
  /**
   * @generated from enum value: OK = 0;
   */
  OK = 0,

  /**
   * @generated from enum value: NOT_FOUND = 1;
   */
  NOT_FOUND = 1,

  /**
   * @generated from enum value: CANCELLING = 2;
   */
  CANCELLING = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(CancelTaskResponse_Status)
proto3.util.setEnumType(CancelTaskResponse_Status, "rbt.v1alpha1.CancelTaskResponse.Status", [
  { no: 0, name: "OK" },
  { no: 1, name: "NOT_FOUND" },
  { no: 2, name: "CANCELLING" },
]);

