// @generated by protoc-gen-es v1.10.1 with parameter "target=ts,import_extension=none"
// @generated from file petclinic/v1/petclinic.proto (package petclinic.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message petclinic.v1.Clinic
 */
export class Clinic extends Message<Clinic> {
  /**
   * @generated from field: optional string owner_index_id = 1;
   */
  ownerIndexId?: string;

  /**
   * @generated from field: optional string veterinarian_index_id = 2;
   */
  veterinarianIndexId?: string;

  constructor(data?: PartialMessage<Clinic>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.Clinic";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "owner_index_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "veterinarian_index_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Clinic {
    return new Clinic().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Clinic {
    return new Clinic().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Clinic {
    return new Clinic().fromJsonString(jsonString, options);
  }

  static equals(a: Clinic | PlainMessage<Clinic> | undefined, b: Clinic | PlainMessage<Clinic> | undefined): boolean {
    return proto3.util.equals(Clinic, a, b);
  }
}

/**
 * @generated from message petclinic.v1.ClinicCreateOwnerRequest
 */
export class ClinicCreateOwnerRequest extends Message<ClinicCreateOwnerRequest> {
  /**
   * @generated from field: optional string first_name = 1;
   */
  firstName?: string;

  /**
   * @generated from field: optional string last_name = 2;
   */
  lastName?: string;

  /**
   * @generated from field: optional string address = 3;
   */
  address?: string;

  /**
   * @generated from field: optional string city = 4;
   */
  city?: string;

  /**
   * @generated from field: optional string telephone = 5;
   */
  telephone?: string;

  constructor(data?: PartialMessage<ClinicCreateOwnerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.ClinicCreateOwnerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "city", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "telephone", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClinicCreateOwnerRequest {
    return new ClinicCreateOwnerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClinicCreateOwnerRequest {
    return new ClinicCreateOwnerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClinicCreateOwnerRequest {
    return new ClinicCreateOwnerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ClinicCreateOwnerRequest | PlainMessage<ClinicCreateOwnerRequest> | undefined, b: ClinicCreateOwnerRequest | PlainMessage<ClinicCreateOwnerRequest> | undefined): boolean {
    return proto3.util.equals(ClinicCreateOwnerRequest, a, b);
  }
}

/**
 * @generated from message petclinic.v1.ClinicCreateOwnerResponse
 */
export class ClinicCreateOwnerResponse extends Message<ClinicCreateOwnerResponse> {
  /**
   * @generated from field: optional string owner_id = 1;
   */
  ownerId?: string;

  constructor(data?: PartialMessage<ClinicCreateOwnerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.ClinicCreateOwnerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "owner_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClinicCreateOwnerResponse {
    return new ClinicCreateOwnerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClinicCreateOwnerResponse {
    return new ClinicCreateOwnerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClinicCreateOwnerResponse {
    return new ClinicCreateOwnerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ClinicCreateOwnerResponse | PlainMessage<ClinicCreateOwnerResponse> | undefined, b: ClinicCreateOwnerResponse | PlainMessage<ClinicCreateOwnerResponse> | undefined): boolean {
    return proto3.util.equals(ClinicCreateOwnerResponse, a, b);
  }
}

/**
 * @generated from message petclinic.v1.ClinicSearchOwnersRequest
 */
export class ClinicSearchOwnersRequest extends Message<ClinicSearchOwnersRequest> {
  /**
   * @generated from field: optional string query = 1;
   */
  query?: string;

  /**
   * @generated from field: optional double limit = 2;
   */
  limit?: number;

  constructor(data?: PartialMessage<ClinicSearchOwnersRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.ClinicSearchOwnersRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "query", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "limit", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClinicSearchOwnersRequest {
    return new ClinicSearchOwnersRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClinicSearchOwnersRequest {
    return new ClinicSearchOwnersRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClinicSearchOwnersRequest {
    return new ClinicSearchOwnersRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ClinicSearchOwnersRequest | PlainMessage<ClinicSearchOwnersRequest> | undefined, b: ClinicSearchOwnersRequest | PlainMessage<ClinicSearchOwnersRequest> | undefined): boolean {
    return proto3.util.equals(ClinicSearchOwnersRequest, a, b);
  }
}

/**
 * @generated from message petclinic.v1.ClinicSearchOwnersResponse
 */
export class ClinicSearchOwnersResponse extends Message<ClinicSearchOwnersResponse> {
  /**
   * @generated from field: optional petclinic.v1.ClinicSearchOwnersResponse.OwnersArray owners = 1;
   */
  owners?: ClinicSearchOwnersResponse_OwnersArray;

  constructor(data?: PartialMessage<ClinicSearchOwnersResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.ClinicSearchOwnersResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "owners", kind: "message", T: ClinicSearchOwnersResponse_OwnersArray, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClinicSearchOwnersResponse {
    return new ClinicSearchOwnersResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClinicSearchOwnersResponse {
    return new ClinicSearchOwnersResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClinicSearchOwnersResponse {
    return new ClinicSearchOwnersResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ClinicSearchOwnersResponse | PlainMessage<ClinicSearchOwnersResponse> | undefined, b: ClinicSearchOwnersResponse | PlainMessage<ClinicSearchOwnersResponse> | undefined): boolean {
    return proto3.util.equals(ClinicSearchOwnersResponse, a, b);
  }
}

/**
 * @generated from message petclinic.v1.ClinicSearchOwnersResponse.OwnersArray
 */
export class ClinicSearchOwnersResponse_OwnersArray extends Message<ClinicSearchOwnersResponse_OwnersArray> {
  /**
   * @generated from field: repeated petclinic.v1.ClinicSearchOwnersResponse.OwnersArray.OwnerCard items = 1;
   */
  items: ClinicSearchOwnersResponse_OwnersArray_OwnerCard[] = [];

  constructor(data?: PartialMessage<ClinicSearchOwnersResponse_OwnersArray>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.ClinicSearchOwnersResponse.OwnersArray";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "items", kind: "message", T: ClinicSearchOwnersResponse_OwnersArray_OwnerCard, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClinicSearchOwnersResponse_OwnersArray {
    return new ClinicSearchOwnersResponse_OwnersArray().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClinicSearchOwnersResponse_OwnersArray {
    return new ClinicSearchOwnersResponse_OwnersArray().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClinicSearchOwnersResponse_OwnersArray {
    return new ClinicSearchOwnersResponse_OwnersArray().fromJsonString(jsonString, options);
  }

  static equals(a: ClinicSearchOwnersResponse_OwnersArray | PlainMessage<ClinicSearchOwnersResponse_OwnersArray> | undefined, b: ClinicSearchOwnersResponse_OwnersArray | PlainMessage<ClinicSearchOwnersResponse_OwnersArray> | undefined): boolean {
    return proto3.util.equals(ClinicSearchOwnersResponse_OwnersArray, a, b);
  }
}

/**
 * @generated from message petclinic.v1.ClinicSearchOwnersResponse.OwnersArray.OwnerCard
 */
export class ClinicSearchOwnersResponse_OwnersArray_OwnerCard extends Message<ClinicSearchOwnersResponse_OwnersArray_OwnerCard> {
  /**
   * @generated from field: optional string owner_id = 1;
   */
  ownerId?: string;

  /**
   * @generated from field: optional string first_name = 2;
   */
  firstName?: string;

  /**
   * @generated from field: optional string last_name = 3;
   */
  lastName?: string;

  /**
   * @generated from field: optional string phone = 4;
   */
  phone?: string;

  constructor(data?: PartialMessage<ClinicSearchOwnersResponse_OwnersArray_OwnerCard>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.ClinicSearchOwnersResponse.OwnersArray.OwnerCard";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "owner_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "phone", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClinicSearchOwnersResponse_OwnersArray_OwnerCard {
    return new ClinicSearchOwnersResponse_OwnersArray_OwnerCard().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClinicSearchOwnersResponse_OwnersArray_OwnerCard {
    return new ClinicSearchOwnersResponse_OwnersArray_OwnerCard().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClinicSearchOwnersResponse_OwnersArray_OwnerCard {
    return new ClinicSearchOwnersResponse_OwnersArray_OwnerCard().fromJsonString(jsonString, options);
  }

  static equals(a: ClinicSearchOwnersResponse_OwnersArray_OwnerCard | PlainMessage<ClinicSearchOwnersResponse_OwnersArray_OwnerCard> | undefined, b: ClinicSearchOwnersResponse_OwnersArray_OwnerCard | PlainMessage<ClinicSearchOwnersResponse_OwnersArray_OwnerCard> | undefined): boolean {
    return proto3.util.equals(ClinicSearchOwnersResponse_OwnersArray_OwnerCard, a, b);
  }
}

/**
 * @generated from message petclinic.v1.ClinicAddVeterinarianRequest
 */
export class ClinicAddVeterinarianRequest extends Message<ClinicAddVeterinarianRequest> {
  /**
   * @generated from field: optional string first_name = 1;
   */
  firstName?: string;

  /**
   * @generated from field: optional string last_name = 2;
   */
  lastName?: string;

  /**
   * @generated from field: optional petclinic.v1.ClinicAddVeterinarianRequest.SpecialtiesArray specialties = 3;
   */
  specialties?: ClinicAddVeterinarianRequest_SpecialtiesArray;

  constructor(data?: PartialMessage<ClinicAddVeterinarianRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.ClinicAddVeterinarianRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "specialties", kind: "message", T: ClinicAddVeterinarianRequest_SpecialtiesArray, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClinicAddVeterinarianRequest {
    return new ClinicAddVeterinarianRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClinicAddVeterinarianRequest {
    return new ClinicAddVeterinarianRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClinicAddVeterinarianRequest {
    return new ClinicAddVeterinarianRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ClinicAddVeterinarianRequest | PlainMessage<ClinicAddVeterinarianRequest> | undefined, b: ClinicAddVeterinarianRequest | PlainMessage<ClinicAddVeterinarianRequest> | undefined): boolean {
    return proto3.util.equals(ClinicAddVeterinarianRequest, a, b);
  }
}

/**
 * @generated from message petclinic.v1.ClinicAddVeterinarianRequest.SpecialtiesArray
 */
export class ClinicAddVeterinarianRequest_SpecialtiesArray extends Message<ClinicAddVeterinarianRequest_SpecialtiesArray> {
  /**
   * @generated from field: repeated string items = 1;
   */
  items: string[] = [];

  constructor(data?: PartialMessage<ClinicAddVeterinarianRequest_SpecialtiesArray>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.ClinicAddVeterinarianRequest.SpecialtiesArray";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "items", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClinicAddVeterinarianRequest_SpecialtiesArray {
    return new ClinicAddVeterinarianRequest_SpecialtiesArray().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClinicAddVeterinarianRequest_SpecialtiesArray {
    return new ClinicAddVeterinarianRequest_SpecialtiesArray().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClinicAddVeterinarianRequest_SpecialtiesArray {
    return new ClinicAddVeterinarianRequest_SpecialtiesArray().fromJsonString(jsonString, options);
  }

  static equals(a: ClinicAddVeterinarianRequest_SpecialtiesArray | PlainMessage<ClinicAddVeterinarianRequest_SpecialtiesArray> | undefined, b: ClinicAddVeterinarianRequest_SpecialtiesArray | PlainMessage<ClinicAddVeterinarianRequest_SpecialtiesArray> | undefined): boolean {
    return proto3.util.equals(ClinicAddVeterinarianRequest_SpecialtiesArray, a, b);
  }
}

/**
 * @generated from message petclinic.v1.ClinicAddVeterinarianResponse
 */
export class ClinicAddVeterinarianResponse extends Message<ClinicAddVeterinarianResponse> {
  /**
   * @generated from field: optional string veterinarian_id = 1;
   */
  veterinarianId?: string;

  constructor(data?: PartialMessage<ClinicAddVeterinarianResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.ClinicAddVeterinarianResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "veterinarian_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClinicAddVeterinarianResponse {
    return new ClinicAddVeterinarianResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClinicAddVeterinarianResponse {
    return new ClinicAddVeterinarianResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClinicAddVeterinarianResponse {
    return new ClinicAddVeterinarianResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ClinicAddVeterinarianResponse | PlainMessage<ClinicAddVeterinarianResponse> | undefined, b: ClinicAddVeterinarianResponse | PlainMessage<ClinicAddVeterinarianResponse> | undefined): boolean {
    return proto3.util.equals(ClinicAddVeterinarianResponse, a, b);
  }
}

/**
 * @generated from message petclinic.v1.ClinicListVeterinariansResponse
 */
export class ClinicListVeterinariansResponse extends Message<ClinicListVeterinariansResponse> {
  /**
   * @generated from field: optional petclinic.v1.ClinicListVeterinariansResponse.VeterinariansArray veterinarians = 1;
   */
  veterinarians?: ClinicListVeterinariansResponse_VeterinariansArray;

  constructor(data?: PartialMessage<ClinicListVeterinariansResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.ClinicListVeterinariansResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "veterinarians", kind: "message", T: ClinicListVeterinariansResponse_VeterinariansArray, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClinicListVeterinariansResponse {
    return new ClinicListVeterinariansResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClinicListVeterinariansResponse {
    return new ClinicListVeterinariansResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClinicListVeterinariansResponse {
    return new ClinicListVeterinariansResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ClinicListVeterinariansResponse | PlainMessage<ClinicListVeterinariansResponse> | undefined, b: ClinicListVeterinariansResponse | PlainMessage<ClinicListVeterinariansResponse> | undefined): boolean {
    return proto3.util.equals(ClinicListVeterinariansResponse, a, b);
  }
}

/**
 * @generated from message petclinic.v1.ClinicListVeterinariansResponse.VeterinariansArray
 */
export class ClinicListVeterinariansResponse_VeterinariansArray extends Message<ClinicListVeterinariansResponse_VeterinariansArray> {
  /**
   * @generated from field: repeated petclinic.v1.ClinicListVeterinariansResponse.VeterinariansArray.VeterinarianCard items = 1;
   */
  items: ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard[] = [];

  constructor(data?: PartialMessage<ClinicListVeterinariansResponse_VeterinariansArray>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.ClinicListVeterinariansResponse.VeterinariansArray";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "items", kind: "message", T: ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClinicListVeterinariansResponse_VeterinariansArray {
    return new ClinicListVeterinariansResponse_VeterinariansArray().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClinicListVeterinariansResponse_VeterinariansArray {
    return new ClinicListVeterinariansResponse_VeterinariansArray().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClinicListVeterinariansResponse_VeterinariansArray {
    return new ClinicListVeterinariansResponse_VeterinariansArray().fromJsonString(jsonString, options);
  }

  static equals(a: ClinicListVeterinariansResponse_VeterinariansArray | PlainMessage<ClinicListVeterinariansResponse_VeterinariansArray> | undefined, b: ClinicListVeterinariansResponse_VeterinariansArray | PlainMessage<ClinicListVeterinariansResponse_VeterinariansArray> | undefined): boolean {
    return proto3.util.equals(ClinicListVeterinariansResponse_VeterinariansArray, a, b);
  }
}

/**
 * @generated from message petclinic.v1.ClinicListVeterinariansResponse.VeterinariansArray.VeterinarianCard
 */
export class ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard extends Message<ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard> {
  /**
   * @generated from field: optional string veterinarian_id = 1;
   */
  veterinarianId?: string;

  /**
   * @generated from field: optional string first_name = 2;
   */
  firstName?: string;

  /**
   * @generated from field: optional string last_name = 3;
   */
  lastName?: string;

  /**
   * @generated from field: optional petclinic.v1.ClinicListVeterinariansResponse.VeterinariansArray.VeterinarianCard.SpecialtiesArray specialties = 4;
   */
  specialties?: ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard_SpecialtiesArray;

  constructor(data?: PartialMessage<ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.ClinicListVeterinariansResponse.VeterinariansArray.VeterinarianCard";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "veterinarian_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "specialties", kind: "message", T: ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard_SpecialtiesArray, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard {
    return new ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard {
    return new ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard {
    return new ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard().fromJsonString(jsonString, options);
  }

  static equals(a: ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard | PlainMessage<ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard> | undefined, b: ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard | PlainMessage<ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard> | undefined): boolean {
    return proto3.util.equals(ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard, a, b);
  }
}

/**
 * @generated from message petclinic.v1.ClinicListVeterinariansResponse.VeterinariansArray.VeterinarianCard.SpecialtiesArray
 */
export class ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard_SpecialtiesArray extends Message<ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard_SpecialtiesArray> {
  /**
   * @generated from field: repeated string items = 1;
   */
  items: string[] = [];

  constructor(data?: PartialMessage<ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard_SpecialtiesArray>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.ClinicListVeterinariansResponse.VeterinariansArray.VeterinarianCard.SpecialtiesArray";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "items", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard_SpecialtiesArray {
    return new ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard_SpecialtiesArray().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard_SpecialtiesArray {
    return new ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard_SpecialtiesArray().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard_SpecialtiesArray {
    return new ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard_SpecialtiesArray().fromJsonString(jsonString, options);
  }

  static equals(a: ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard_SpecialtiesArray | PlainMessage<ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard_SpecialtiesArray> | undefined, b: ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard_SpecialtiesArray | PlainMessage<ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard_SpecialtiesArray> | undefined): boolean {
    return proto3.util.equals(ClinicListVeterinariansResponse_VeterinariansArray_VeterinarianCard_SpecialtiesArray, a, b);
  }
}

/**
 * @generated from message petclinic.v1.Owner
 */
export class Owner extends Message<Owner> {
  /**
   * @generated from field: optional string first_name = 1;
   */
  firstName?: string;

  /**
   * @generated from field: optional string last_name = 2;
   */
  lastName?: string;

  /**
   * @generated from field: optional string address = 3;
   */
  address?: string;

  /**
   * @generated from field: optional string city = 4;
   */
  city?: string;

  /**
   * @generated from field: optional string telephone = 5;
   */
  telephone?: string;

  /**
   * @generated from field: optional string pet_index_id = 6;
   */
  petIndexId?: string;

  constructor(data?: PartialMessage<Owner>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.Owner";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "city", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "telephone", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "pet_index_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Owner {
    return new Owner().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Owner {
    return new Owner().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Owner {
    return new Owner().fromJsonString(jsonString, options);
  }

  static equals(a: Owner | PlainMessage<Owner> | undefined, b: Owner | PlainMessage<Owner> | undefined): boolean {
    return proto3.util.equals(Owner, a, b);
  }
}

/**
 * @generated from message petclinic.v1.OwnerRegisterRequest
 */
export class OwnerRegisterRequest extends Message<OwnerRegisterRequest> {
  /**
   * @generated from field: optional string first_name = 1;
   */
  firstName?: string;

  /**
   * @generated from field: optional string last_name = 2;
   */
  lastName?: string;

  /**
   * @generated from field: optional string address = 3;
   */
  address?: string;

  /**
   * @generated from field: optional string city = 4;
   */
  city?: string;

  /**
   * @generated from field: optional string telephone = 5;
   */
  telephone?: string;

  constructor(data?: PartialMessage<OwnerRegisterRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.OwnerRegisterRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "city", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "telephone", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OwnerRegisterRequest {
    return new OwnerRegisterRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OwnerRegisterRequest {
    return new OwnerRegisterRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OwnerRegisterRequest {
    return new OwnerRegisterRequest().fromJsonString(jsonString, options);
  }

  static equals(a: OwnerRegisterRequest | PlainMessage<OwnerRegisterRequest> | undefined, b: OwnerRegisterRequest | PlainMessage<OwnerRegisterRequest> | undefined): boolean {
    return proto3.util.equals(OwnerRegisterRequest, a, b);
  }
}

/**
 * @generated from message petclinic.v1.OwnerUpdateRequest
 */
export class OwnerUpdateRequest extends Message<OwnerUpdateRequest> {
  /**
   * @generated from field: optional string first_name = 1;
   */
  firstName?: string;

  /**
   * @generated from field: optional string last_name = 2;
   */
  lastName?: string;

  /**
   * @generated from field: optional string address = 3;
   */
  address?: string;

  /**
   * @generated from field: optional string city = 4;
   */
  city?: string;

  /**
   * @generated from field: optional string telephone = 5;
   */
  telephone?: string;

  constructor(data?: PartialMessage<OwnerUpdateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.OwnerUpdateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "city", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "telephone", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OwnerUpdateRequest {
    return new OwnerUpdateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OwnerUpdateRequest {
    return new OwnerUpdateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OwnerUpdateRequest {
    return new OwnerUpdateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: OwnerUpdateRequest | PlainMessage<OwnerUpdateRequest> | undefined, b: OwnerUpdateRequest | PlainMessage<OwnerUpdateRequest> | undefined): boolean {
    return proto3.util.equals(OwnerUpdateRequest, a, b);
  }
}

/**
 * @generated from message petclinic.v1.OwnerAddPetRequest
 */
export class OwnerAddPetRequest extends Message<OwnerAddPetRequest> {
  /**
   * @generated from field: optional string name = 1;
   */
  name?: string;

  /**
   * @generated from field: optional string pet_type = 2;
   */
  petType?: string;

  /**
   * @generated from field: optional string birthday = 3;
   */
  birthday?: string;

  constructor(data?: PartialMessage<OwnerAddPetRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.OwnerAddPetRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "pet_type", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "birthday", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OwnerAddPetRequest {
    return new OwnerAddPetRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OwnerAddPetRequest {
    return new OwnerAddPetRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OwnerAddPetRequest {
    return new OwnerAddPetRequest().fromJsonString(jsonString, options);
  }

  static equals(a: OwnerAddPetRequest | PlainMessage<OwnerAddPetRequest> | undefined, b: OwnerAddPetRequest | PlainMessage<OwnerAddPetRequest> | undefined): boolean {
    return proto3.util.equals(OwnerAddPetRequest, a, b);
  }
}

/**
 * @generated from message petclinic.v1.OwnerAddPetResponse
 */
export class OwnerAddPetResponse extends Message<OwnerAddPetResponse> {
  /**
   * @generated from field: optional string pet_id = 1;
   */
  petId?: string;

  constructor(data?: PartialMessage<OwnerAddPetResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.OwnerAddPetResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pet_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OwnerAddPetResponse {
    return new OwnerAddPetResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OwnerAddPetResponse {
    return new OwnerAddPetResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OwnerAddPetResponse {
    return new OwnerAddPetResponse().fromJsonString(jsonString, options);
  }

  static equals(a: OwnerAddPetResponse | PlainMessage<OwnerAddPetResponse> | undefined, b: OwnerAddPetResponse | PlainMessage<OwnerAddPetResponse> | undefined): boolean {
    return proto3.util.equals(OwnerAddPetResponse, a, b);
  }
}

/**
 * @generated from message petclinic.v1.OwnerDetailsResponse
 */
export class OwnerDetailsResponse extends Message<OwnerDetailsResponse> {
  /**
   * @generated from field: optional petclinic.v1.OwnerDetailsResponse.Owner owner = 1;
   */
  owner?: OwnerDetailsResponse_Owner;

  /**
   * @generated from field: optional string address = 2;
   */
  address?: string;

  /**
   * @generated from field: optional string city = 3;
   */
  city?: string;

  /**
   * @generated from field: optional petclinic.v1.OwnerDetailsResponse.PetsArray pets = 4;
   */
  pets?: OwnerDetailsResponse_PetsArray;

  constructor(data?: PartialMessage<OwnerDetailsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.OwnerDetailsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "owner", kind: "message", T: OwnerDetailsResponse_Owner, opt: true },
    { no: 2, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "city", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "pets", kind: "message", T: OwnerDetailsResponse_PetsArray, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OwnerDetailsResponse {
    return new OwnerDetailsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OwnerDetailsResponse {
    return new OwnerDetailsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OwnerDetailsResponse {
    return new OwnerDetailsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: OwnerDetailsResponse | PlainMessage<OwnerDetailsResponse> | undefined, b: OwnerDetailsResponse | PlainMessage<OwnerDetailsResponse> | undefined): boolean {
    return proto3.util.equals(OwnerDetailsResponse, a, b);
  }
}

/**
 * @generated from message petclinic.v1.OwnerDetailsResponse.Owner
 */
export class OwnerDetailsResponse_Owner extends Message<OwnerDetailsResponse_Owner> {
  /**
   * @generated from field: optional string owner_id = 1;
   */
  ownerId?: string;

  /**
   * @generated from field: optional string first_name = 2;
   */
  firstName?: string;

  /**
   * @generated from field: optional string last_name = 3;
   */
  lastName?: string;

  /**
   * @generated from field: optional string phone = 4;
   */
  phone?: string;

  constructor(data?: PartialMessage<OwnerDetailsResponse_Owner>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.OwnerDetailsResponse.Owner";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "owner_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "phone", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OwnerDetailsResponse_Owner {
    return new OwnerDetailsResponse_Owner().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OwnerDetailsResponse_Owner {
    return new OwnerDetailsResponse_Owner().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OwnerDetailsResponse_Owner {
    return new OwnerDetailsResponse_Owner().fromJsonString(jsonString, options);
  }

  static equals(a: OwnerDetailsResponse_Owner | PlainMessage<OwnerDetailsResponse_Owner> | undefined, b: OwnerDetailsResponse_Owner | PlainMessage<OwnerDetailsResponse_Owner> | undefined): boolean {
    return proto3.util.equals(OwnerDetailsResponse_Owner, a, b);
  }
}

/**
 * @generated from message petclinic.v1.OwnerDetailsResponse.PetsArray
 */
export class OwnerDetailsResponse_PetsArray extends Message<OwnerDetailsResponse_PetsArray> {
  /**
   * @generated from field: repeated petclinic.v1.OwnerDetailsResponse.PetsArray.PetCard items = 1;
   */
  items: OwnerDetailsResponse_PetsArray_PetCard[] = [];

  constructor(data?: PartialMessage<OwnerDetailsResponse_PetsArray>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.OwnerDetailsResponse.PetsArray";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "items", kind: "message", T: OwnerDetailsResponse_PetsArray_PetCard, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OwnerDetailsResponse_PetsArray {
    return new OwnerDetailsResponse_PetsArray().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OwnerDetailsResponse_PetsArray {
    return new OwnerDetailsResponse_PetsArray().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OwnerDetailsResponse_PetsArray {
    return new OwnerDetailsResponse_PetsArray().fromJsonString(jsonString, options);
  }

  static equals(a: OwnerDetailsResponse_PetsArray | PlainMessage<OwnerDetailsResponse_PetsArray> | undefined, b: OwnerDetailsResponse_PetsArray | PlainMessage<OwnerDetailsResponse_PetsArray> | undefined): boolean {
    return proto3.util.equals(OwnerDetailsResponse_PetsArray, a, b);
  }
}

/**
 * @generated from message petclinic.v1.OwnerDetailsResponse.PetsArray.PetCard
 */
export class OwnerDetailsResponse_PetsArray_PetCard extends Message<OwnerDetailsResponse_PetsArray_PetCard> {
  /**
   * @generated from field: optional string pet_id = 1;
   */
  petId?: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: optional string pet_type = 3;
   */
  petType?: string;

  /**
   * @generated from field: optional string birthday = 4;
   */
  birthday?: string;

  constructor(data?: PartialMessage<OwnerDetailsResponse_PetsArray_PetCard>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.OwnerDetailsResponse.PetsArray.PetCard";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pet_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "pet_type", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "birthday", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OwnerDetailsResponse_PetsArray_PetCard {
    return new OwnerDetailsResponse_PetsArray_PetCard().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OwnerDetailsResponse_PetsArray_PetCard {
    return new OwnerDetailsResponse_PetsArray_PetCard().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OwnerDetailsResponse_PetsArray_PetCard {
    return new OwnerDetailsResponse_PetsArray_PetCard().fromJsonString(jsonString, options);
  }

  static equals(a: OwnerDetailsResponse_PetsArray_PetCard | PlainMessage<OwnerDetailsResponse_PetsArray_PetCard> | undefined, b: OwnerDetailsResponse_PetsArray_PetCard | PlainMessage<OwnerDetailsResponse_PetsArray_PetCard> | undefined): boolean {
    return proto3.util.equals(OwnerDetailsResponse_PetsArray_PetCard, a, b);
  }
}

/**
 * @generated from message petclinic.v1.Pet
 */
export class Pet extends Message<Pet> {
  /**
   * @generated from field: optional string owner_id = 1;
   */
  ownerId?: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: optional string pet_type = 3;
   */
  petType?: string;

  /**
   * @generated from field: optional string birthday = 4;
   */
  birthday?: string;

  /**
   * @generated from field: optional petclinic.v1.Pet.VisitsArray visits = 5;
   */
  visits?: Pet_VisitsArray;

  constructor(data?: PartialMessage<Pet>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.Pet";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "owner_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "pet_type", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "birthday", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "visits", kind: "message", T: Pet_VisitsArray, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Pet {
    return new Pet().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Pet {
    return new Pet().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Pet {
    return new Pet().fromJsonString(jsonString, options);
  }

  static equals(a: Pet | PlainMessage<Pet> | undefined, b: Pet | PlainMessage<Pet> | undefined): boolean {
    return proto3.util.equals(Pet, a, b);
  }
}

/**
 * @generated from message petclinic.v1.Pet.VisitsArray
 */
export class Pet_VisitsArray extends Message<Pet_VisitsArray> {
  /**
   * @generated from field: repeated petclinic.v1.Pet.VisitsArray.VisitRecord items = 1;
   */
  items: Pet_VisitsArray_VisitRecord[] = [];

  constructor(data?: PartialMessage<Pet_VisitsArray>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.Pet.VisitsArray";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "items", kind: "message", T: Pet_VisitsArray_VisitRecord, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Pet_VisitsArray {
    return new Pet_VisitsArray().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Pet_VisitsArray {
    return new Pet_VisitsArray().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Pet_VisitsArray {
    return new Pet_VisitsArray().fromJsonString(jsonString, options);
  }

  static equals(a: Pet_VisitsArray | PlainMessage<Pet_VisitsArray> | undefined, b: Pet_VisitsArray | PlainMessage<Pet_VisitsArray> | undefined): boolean {
    return proto3.util.equals(Pet_VisitsArray, a, b);
  }
}

/**
 * @generated from message petclinic.v1.Pet.VisitsArray.VisitRecord
 */
export class Pet_VisitsArray_VisitRecord extends Message<Pet_VisitsArray_VisitRecord> {
  /**
   * @generated from field: optional string visit_date = 1;
   */
  visitDate?: string;

  /**
   * @generated from field: optional string description = 2;
   */
  description?: string;

  constructor(data?: PartialMessage<Pet_VisitsArray_VisitRecord>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.Pet.VisitsArray.VisitRecord";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "visit_date", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Pet_VisitsArray_VisitRecord {
    return new Pet_VisitsArray_VisitRecord().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Pet_VisitsArray_VisitRecord {
    return new Pet_VisitsArray_VisitRecord().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Pet_VisitsArray_VisitRecord {
    return new Pet_VisitsArray_VisitRecord().fromJsonString(jsonString, options);
  }

  static equals(a: Pet_VisitsArray_VisitRecord | PlainMessage<Pet_VisitsArray_VisitRecord> | undefined, b: Pet_VisitsArray_VisitRecord | PlainMessage<Pet_VisitsArray_VisitRecord> | undefined): boolean {
    return proto3.util.equals(Pet_VisitsArray_VisitRecord, a, b);
  }
}

/**
 * @generated from message petclinic.v1.PetRegisterRequest
 */
export class PetRegisterRequest extends Message<PetRegisterRequest> {
  /**
   * @generated from field: optional string owner_id = 1;
   */
  ownerId?: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: optional string pet_type = 3;
   */
  petType?: string;

  /**
   * @generated from field: optional string birthday = 4;
   */
  birthday?: string;

  constructor(data?: PartialMessage<PetRegisterRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.PetRegisterRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "owner_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "pet_type", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "birthday", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PetRegisterRequest {
    return new PetRegisterRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PetRegisterRequest {
    return new PetRegisterRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PetRegisterRequest {
    return new PetRegisterRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PetRegisterRequest | PlainMessage<PetRegisterRequest> | undefined, b: PetRegisterRequest | PlainMessage<PetRegisterRequest> | undefined): boolean {
    return proto3.util.equals(PetRegisterRequest, a, b);
  }
}

/**
 * @generated from message petclinic.v1.PetUpdateRequest
 */
export class PetUpdateRequest extends Message<PetUpdateRequest> {
  /**
   * @generated from field: optional string name = 1;
   */
  name?: string;

  /**
   * @generated from field: optional string pet_type = 2;
   */
  petType?: string;

  /**
   * @generated from field: optional string birthday = 3;
   */
  birthday?: string;

  constructor(data?: PartialMessage<PetUpdateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.PetUpdateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "pet_type", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "birthday", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PetUpdateRequest {
    return new PetUpdateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PetUpdateRequest {
    return new PetUpdateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PetUpdateRequest {
    return new PetUpdateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PetUpdateRequest | PlainMessage<PetUpdateRequest> | undefined, b: PetUpdateRequest | PlainMessage<PetUpdateRequest> | undefined): boolean {
    return proto3.util.equals(PetUpdateRequest, a, b);
  }
}

/**
 * @generated from message petclinic.v1.PetRecordVisitRequest
 */
export class PetRecordVisitRequest extends Message<PetRecordVisitRequest> {
  /**
   * @generated from field: optional string visit_date = 1;
   */
  visitDate?: string;

  /**
   * @generated from field: optional string description = 2;
   */
  description?: string;

  constructor(data?: PartialMessage<PetRecordVisitRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.PetRecordVisitRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "visit_date", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PetRecordVisitRequest {
    return new PetRecordVisitRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PetRecordVisitRequest {
    return new PetRecordVisitRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PetRecordVisitRequest {
    return new PetRecordVisitRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PetRecordVisitRequest | PlainMessage<PetRecordVisitRequest> | undefined, b: PetRecordVisitRequest | PlainMessage<PetRecordVisitRequest> | undefined): boolean {
    return proto3.util.equals(PetRecordVisitRequest, a, b);
  }
}

/**
 * @generated from message petclinic.v1.PetDetailsResponse
 */
export class PetDetailsResponse extends Message<PetDetailsResponse> {
  /**
   * @generated from field: optional petclinic.v1.PetDetailsResponse.Pet pet = 1;
   */
  pet?: PetDetailsResponse_Pet;

  /**
   * @generated from field: optional string owner_id = 2;
   */
  ownerId?: string;

  /**
   * @generated from field: optional petclinic.v1.PetDetailsResponse.VisitsArray visits = 3;
   */
  visits?: PetDetailsResponse_VisitsArray;

  constructor(data?: PartialMessage<PetDetailsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.PetDetailsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pet", kind: "message", T: PetDetailsResponse_Pet, opt: true },
    { no: 2, name: "owner_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "visits", kind: "message", T: PetDetailsResponse_VisitsArray, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PetDetailsResponse {
    return new PetDetailsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PetDetailsResponse {
    return new PetDetailsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PetDetailsResponse {
    return new PetDetailsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: PetDetailsResponse | PlainMessage<PetDetailsResponse> | undefined, b: PetDetailsResponse | PlainMessage<PetDetailsResponse> | undefined): boolean {
    return proto3.util.equals(PetDetailsResponse, a, b);
  }
}

/**
 * @generated from message petclinic.v1.PetDetailsResponse.Pet
 */
export class PetDetailsResponse_Pet extends Message<PetDetailsResponse_Pet> {
  /**
   * @generated from field: optional string pet_id = 1;
   */
  petId?: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: optional string pet_type = 3;
   */
  petType?: string;

  /**
   * @generated from field: optional string birthday = 4;
   */
  birthday?: string;

  constructor(data?: PartialMessage<PetDetailsResponse_Pet>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.PetDetailsResponse.Pet";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pet_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "pet_type", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "birthday", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PetDetailsResponse_Pet {
    return new PetDetailsResponse_Pet().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PetDetailsResponse_Pet {
    return new PetDetailsResponse_Pet().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PetDetailsResponse_Pet {
    return new PetDetailsResponse_Pet().fromJsonString(jsonString, options);
  }

  static equals(a: PetDetailsResponse_Pet | PlainMessage<PetDetailsResponse_Pet> | undefined, b: PetDetailsResponse_Pet | PlainMessage<PetDetailsResponse_Pet> | undefined): boolean {
    return proto3.util.equals(PetDetailsResponse_Pet, a, b);
  }
}

/**
 * @generated from message petclinic.v1.PetDetailsResponse.VisitsArray
 */
export class PetDetailsResponse_VisitsArray extends Message<PetDetailsResponse_VisitsArray> {
  /**
   * @generated from field: repeated petclinic.v1.PetDetailsResponse.VisitsArray.VisitRecord items = 1;
   */
  items: PetDetailsResponse_VisitsArray_VisitRecord[] = [];

  constructor(data?: PartialMessage<PetDetailsResponse_VisitsArray>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.PetDetailsResponse.VisitsArray";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "items", kind: "message", T: PetDetailsResponse_VisitsArray_VisitRecord, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PetDetailsResponse_VisitsArray {
    return new PetDetailsResponse_VisitsArray().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PetDetailsResponse_VisitsArray {
    return new PetDetailsResponse_VisitsArray().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PetDetailsResponse_VisitsArray {
    return new PetDetailsResponse_VisitsArray().fromJsonString(jsonString, options);
  }

  static equals(a: PetDetailsResponse_VisitsArray | PlainMessage<PetDetailsResponse_VisitsArray> | undefined, b: PetDetailsResponse_VisitsArray | PlainMessage<PetDetailsResponse_VisitsArray> | undefined): boolean {
    return proto3.util.equals(PetDetailsResponse_VisitsArray, a, b);
  }
}

/**
 * @generated from message petclinic.v1.PetDetailsResponse.VisitsArray.VisitRecord
 */
export class PetDetailsResponse_VisitsArray_VisitRecord extends Message<PetDetailsResponse_VisitsArray_VisitRecord> {
  /**
   * @generated from field: optional string visit_date = 1;
   */
  visitDate?: string;

  /**
   * @generated from field: optional string description = 2;
   */
  description?: string;

  constructor(data?: PartialMessage<PetDetailsResponse_VisitsArray_VisitRecord>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.PetDetailsResponse.VisitsArray.VisitRecord";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "visit_date", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PetDetailsResponse_VisitsArray_VisitRecord {
    return new PetDetailsResponse_VisitsArray_VisitRecord().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PetDetailsResponse_VisitsArray_VisitRecord {
    return new PetDetailsResponse_VisitsArray_VisitRecord().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PetDetailsResponse_VisitsArray_VisitRecord {
    return new PetDetailsResponse_VisitsArray_VisitRecord().fromJsonString(jsonString, options);
  }

  static equals(a: PetDetailsResponse_VisitsArray_VisitRecord | PlainMessage<PetDetailsResponse_VisitsArray_VisitRecord> | undefined, b: PetDetailsResponse_VisitsArray_VisitRecord | PlainMessage<PetDetailsResponse_VisitsArray_VisitRecord> | undefined): boolean {
    return proto3.util.equals(PetDetailsResponse_VisitsArray_VisitRecord, a, b);
  }
}

/**
 * @generated from message petclinic.v1.Veterinarian
 */
export class Veterinarian extends Message<Veterinarian> {
  /**
   * @generated from field: optional string first_name = 1;
   */
  firstName?: string;

  /**
   * @generated from field: optional string last_name = 2;
   */
  lastName?: string;

  /**
   * @generated from field: optional petclinic.v1.Veterinarian.SpecialtiesArray specialties = 3;
   */
  specialties?: Veterinarian_SpecialtiesArray;

  constructor(data?: PartialMessage<Veterinarian>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.Veterinarian";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "specialties", kind: "message", T: Veterinarian_SpecialtiesArray, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Veterinarian {
    return new Veterinarian().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Veterinarian {
    return new Veterinarian().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Veterinarian {
    return new Veterinarian().fromJsonString(jsonString, options);
  }

  static equals(a: Veterinarian | PlainMessage<Veterinarian> | undefined, b: Veterinarian | PlainMessage<Veterinarian> | undefined): boolean {
    return proto3.util.equals(Veterinarian, a, b);
  }
}

/**
 * @generated from message petclinic.v1.Veterinarian.SpecialtiesArray
 */
export class Veterinarian_SpecialtiesArray extends Message<Veterinarian_SpecialtiesArray> {
  /**
   * @generated from field: repeated string items = 1;
   */
  items: string[] = [];

  constructor(data?: PartialMessage<Veterinarian_SpecialtiesArray>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.Veterinarian.SpecialtiesArray";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "items", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Veterinarian_SpecialtiesArray {
    return new Veterinarian_SpecialtiesArray().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Veterinarian_SpecialtiesArray {
    return new Veterinarian_SpecialtiesArray().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Veterinarian_SpecialtiesArray {
    return new Veterinarian_SpecialtiesArray().fromJsonString(jsonString, options);
  }

  static equals(a: Veterinarian_SpecialtiesArray | PlainMessage<Veterinarian_SpecialtiesArray> | undefined, b: Veterinarian_SpecialtiesArray | PlainMessage<Veterinarian_SpecialtiesArray> | undefined): boolean {
    return proto3.util.equals(Veterinarian_SpecialtiesArray, a, b);
  }
}

/**
 * @generated from message petclinic.v1.VeterinarianRegisterRequest
 */
export class VeterinarianRegisterRequest extends Message<VeterinarianRegisterRequest> {
  /**
   * @generated from field: optional string first_name = 1;
   */
  firstName?: string;

  /**
   * @generated from field: optional string last_name = 2;
   */
  lastName?: string;

  /**
   * @generated from field: optional petclinic.v1.VeterinarianRegisterRequest.SpecialtiesArray specialties = 3;
   */
  specialties?: VeterinarianRegisterRequest_SpecialtiesArray;

  constructor(data?: PartialMessage<VeterinarianRegisterRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.VeterinarianRegisterRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "specialties", kind: "message", T: VeterinarianRegisterRequest_SpecialtiesArray, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VeterinarianRegisterRequest {
    return new VeterinarianRegisterRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VeterinarianRegisterRequest {
    return new VeterinarianRegisterRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VeterinarianRegisterRequest {
    return new VeterinarianRegisterRequest().fromJsonString(jsonString, options);
  }

  static equals(a: VeterinarianRegisterRequest | PlainMessage<VeterinarianRegisterRequest> | undefined, b: VeterinarianRegisterRequest | PlainMessage<VeterinarianRegisterRequest> | undefined): boolean {
    return proto3.util.equals(VeterinarianRegisterRequest, a, b);
  }
}

/**
 * @generated from message petclinic.v1.VeterinarianRegisterRequest.SpecialtiesArray
 */
export class VeterinarianRegisterRequest_SpecialtiesArray extends Message<VeterinarianRegisterRequest_SpecialtiesArray> {
  /**
   * @generated from field: repeated string items = 1;
   */
  items: string[] = [];

  constructor(data?: PartialMessage<VeterinarianRegisterRequest_SpecialtiesArray>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.VeterinarianRegisterRequest.SpecialtiesArray";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "items", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VeterinarianRegisterRequest_SpecialtiesArray {
    return new VeterinarianRegisterRequest_SpecialtiesArray().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VeterinarianRegisterRequest_SpecialtiesArray {
    return new VeterinarianRegisterRequest_SpecialtiesArray().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VeterinarianRegisterRequest_SpecialtiesArray {
    return new VeterinarianRegisterRequest_SpecialtiesArray().fromJsonString(jsonString, options);
  }

  static equals(a: VeterinarianRegisterRequest_SpecialtiesArray | PlainMessage<VeterinarianRegisterRequest_SpecialtiesArray> | undefined, b: VeterinarianRegisterRequest_SpecialtiesArray | PlainMessage<VeterinarianRegisterRequest_SpecialtiesArray> | undefined): boolean {
    return proto3.util.equals(VeterinarianRegisterRequest_SpecialtiesArray, a, b);
  }
}

/**
 * @generated from message petclinic.v1.VeterinarianUpdateRequest
 */
export class VeterinarianUpdateRequest extends Message<VeterinarianUpdateRequest> {
  /**
   * @generated from field: optional string first_name = 1;
   */
  firstName?: string;

  /**
   * @generated from field: optional string last_name = 2;
   */
  lastName?: string;

  /**
   * @generated from field: optional petclinic.v1.VeterinarianUpdateRequest.SpecialtiesArray specialties = 3;
   */
  specialties?: VeterinarianUpdateRequest_SpecialtiesArray;

  constructor(data?: PartialMessage<VeterinarianUpdateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.VeterinarianUpdateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "specialties", kind: "message", T: VeterinarianUpdateRequest_SpecialtiesArray, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VeterinarianUpdateRequest {
    return new VeterinarianUpdateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VeterinarianUpdateRequest {
    return new VeterinarianUpdateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VeterinarianUpdateRequest {
    return new VeterinarianUpdateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: VeterinarianUpdateRequest | PlainMessage<VeterinarianUpdateRequest> | undefined, b: VeterinarianUpdateRequest | PlainMessage<VeterinarianUpdateRequest> | undefined): boolean {
    return proto3.util.equals(VeterinarianUpdateRequest, a, b);
  }
}

/**
 * @generated from message petclinic.v1.VeterinarianUpdateRequest.SpecialtiesArray
 */
export class VeterinarianUpdateRequest_SpecialtiesArray extends Message<VeterinarianUpdateRequest_SpecialtiesArray> {
  /**
   * @generated from field: repeated string items = 1;
   */
  items: string[] = [];

  constructor(data?: PartialMessage<VeterinarianUpdateRequest_SpecialtiesArray>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.VeterinarianUpdateRequest.SpecialtiesArray";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "items", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VeterinarianUpdateRequest_SpecialtiesArray {
    return new VeterinarianUpdateRequest_SpecialtiesArray().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VeterinarianUpdateRequest_SpecialtiesArray {
    return new VeterinarianUpdateRequest_SpecialtiesArray().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VeterinarianUpdateRequest_SpecialtiesArray {
    return new VeterinarianUpdateRequest_SpecialtiesArray().fromJsonString(jsonString, options);
  }

  static equals(a: VeterinarianUpdateRequest_SpecialtiesArray | PlainMessage<VeterinarianUpdateRequest_SpecialtiesArray> | undefined, b: VeterinarianUpdateRequest_SpecialtiesArray | PlainMessage<VeterinarianUpdateRequest_SpecialtiesArray> | undefined): boolean {
    return proto3.util.equals(VeterinarianUpdateRequest_SpecialtiesArray, a, b);
  }
}

/**
 * @generated from message petclinic.v1.VeterinarianDetailsResponse
 */
export class VeterinarianDetailsResponse extends Message<VeterinarianDetailsResponse> {
  /**
   * @generated from field: optional petclinic.v1.VeterinarianDetailsResponse.Veterinarian veterinarian = 1;
   */
  veterinarian?: VeterinarianDetailsResponse_Veterinarian;

  constructor(data?: PartialMessage<VeterinarianDetailsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.VeterinarianDetailsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "veterinarian", kind: "message", T: VeterinarianDetailsResponse_Veterinarian, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VeterinarianDetailsResponse {
    return new VeterinarianDetailsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VeterinarianDetailsResponse {
    return new VeterinarianDetailsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VeterinarianDetailsResponse {
    return new VeterinarianDetailsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: VeterinarianDetailsResponse | PlainMessage<VeterinarianDetailsResponse> | undefined, b: VeterinarianDetailsResponse | PlainMessage<VeterinarianDetailsResponse> | undefined): boolean {
    return proto3.util.equals(VeterinarianDetailsResponse, a, b);
  }
}

/**
 * @generated from message petclinic.v1.VeterinarianDetailsResponse.Veterinarian
 */
export class VeterinarianDetailsResponse_Veterinarian extends Message<VeterinarianDetailsResponse_Veterinarian> {
  /**
   * @generated from field: optional string veterinarian_id = 1;
   */
  veterinarianId?: string;

  /**
   * @generated from field: optional string first_name = 2;
   */
  firstName?: string;

  /**
   * @generated from field: optional string last_name = 3;
   */
  lastName?: string;

  /**
   * @generated from field: optional petclinic.v1.VeterinarianDetailsResponse.Veterinarian.SpecialtiesArray specialties = 4;
   */
  specialties?: VeterinarianDetailsResponse_Veterinarian_SpecialtiesArray;

  constructor(data?: PartialMessage<VeterinarianDetailsResponse_Veterinarian>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.VeterinarianDetailsResponse.Veterinarian";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "veterinarian_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "specialties", kind: "message", T: VeterinarianDetailsResponse_Veterinarian_SpecialtiesArray, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VeterinarianDetailsResponse_Veterinarian {
    return new VeterinarianDetailsResponse_Veterinarian().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VeterinarianDetailsResponse_Veterinarian {
    return new VeterinarianDetailsResponse_Veterinarian().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VeterinarianDetailsResponse_Veterinarian {
    return new VeterinarianDetailsResponse_Veterinarian().fromJsonString(jsonString, options);
  }

  static equals(a: VeterinarianDetailsResponse_Veterinarian | PlainMessage<VeterinarianDetailsResponse_Veterinarian> | undefined, b: VeterinarianDetailsResponse_Veterinarian | PlainMessage<VeterinarianDetailsResponse_Veterinarian> | undefined): boolean {
    return proto3.util.equals(VeterinarianDetailsResponse_Veterinarian, a, b);
  }
}

/**
 * @generated from message petclinic.v1.VeterinarianDetailsResponse.Veterinarian.SpecialtiesArray
 */
export class VeterinarianDetailsResponse_Veterinarian_SpecialtiesArray extends Message<VeterinarianDetailsResponse_Veterinarian_SpecialtiesArray> {
  /**
   * @generated from field: repeated string items = 1;
   */
  items: string[] = [];

  constructor(data?: PartialMessage<VeterinarianDetailsResponse_Veterinarian_SpecialtiesArray>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "petclinic.v1.VeterinarianDetailsResponse.Veterinarian.SpecialtiesArray";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "items", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VeterinarianDetailsResponse_Veterinarian_SpecialtiesArray {
    return new VeterinarianDetailsResponse_Veterinarian_SpecialtiesArray().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VeterinarianDetailsResponse_Veterinarian_SpecialtiesArray {
    return new VeterinarianDetailsResponse_Veterinarian_SpecialtiesArray().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VeterinarianDetailsResponse_Veterinarian_SpecialtiesArray {
    return new VeterinarianDetailsResponse_Veterinarian_SpecialtiesArray().fromJsonString(jsonString, options);
  }

  static equals(a: VeterinarianDetailsResponse_Veterinarian_SpecialtiesArray | PlainMessage<VeterinarianDetailsResponse_Veterinarian_SpecialtiesArray> | undefined, b: VeterinarianDetailsResponse_Veterinarian_SpecialtiesArray | PlainMessage<VeterinarianDetailsResponse_Veterinarian_SpecialtiesArray> | undefined): boolean {
    return proto3.util.equals(VeterinarianDetailsResponse_Veterinarian_SpecialtiesArray, a, b);
  }
}

